export const jobs = [
    {
        id: 1,
        title: 'Can you please fix my fridge',
        desc: 'the cooler of the fridge is broken',
        photo: '',
        poster_id: '',
        assigned_id: '',
        salary: 1000,
        tags: ['fridge', 'mechanic'],
        created: new Date('2021-10-02'),
        resources: '',
        isAssigned: false,
        isComplete: true,
    },
    {
        id: 2,
        title: ' Can you fix the car (ASAP)',
        desc: 'the radiator is broken',
        photo: '',
        poster_id: '',
        assigned_id: '',
        salary: 2000,
        tags: ['car', 'mechanic'],
        created: new Date('2021-10-10'),
        resources: '',
        isAssigned: true,
        isComplete: false,
    },
    {
        id: 3,
        title: 'can you please fix my fan',
        desc: '',
        photo: '',
        poster_id: '',
        assigned_id: '',
        salary: 1000,
        tags: ['fan', 'electrician'],
        created: new Date('2021-09-10'),
        resources: '',
        isAssigned: true,
        isComplete: true,
    },
    {
        id: 4,
        title: 'I need flowers for the wedding',
        desc: '',
        photo: '',
        poster_id: '',
        assigned_id: '',
        salary: 500,
        tags: ['flowers', 'garlands', 'florist'],
        created: new Date('2021-10-21'),
        resources: '',
        isAssigned: true,
        isComplete: false,
    },
    {
        id: 5,
        title: 'Need a maid to clean my house for a week',
        desc: '',
        photo: '',
        poster_id: '',
        assigned_id: '',
        salary: 12000,
        tags: ['maid', 'sweeping', 'mopping'],
        created: new Date('2021-10-23'),
        resources: '',
        isAssigned: false,
        isComplete: false,
    },
];
